### ISSUE TITLE
URLs and filenaming discussion in 03_foundations

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-data-intro#33]
In reading through the 03_Foundations section, I found the filenaming discussion hard to understand. I deal constantly with filenaming in my work, but I didn't understand the principles being presented here well enough to know how to revise. As a librarian reading that section, I also had no idea of how to name a file after reading it. I'll try to come back to this topic after reviewing the entire lc_data_intro episodes.

**Comment by jt14den** [comment]
@emcaulay I agree. At the SLA LC workshop, I used a part of this instead: http://www.datacarpentry.org/rr-organization1/01-file-naming/

It's written with a `R` application as examples, but the concepts are laid out pretty well. We could edit out the R files and refactor for this episode. What do you think?

**Comment by ccronje** [comment]
@emcaulay @jt14den I like the approach of http://www.datacarpentry.org/rr-organization1/01-file-naming/ (taken from https://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf). It would be good to rework this section as you've suggested.

**Comment by drjwbaker** [comment]
Bumping. Any maintainer want to take this?

**Comment by ccronje** [comment]
Recommend improving the file naming section.

- @jt14den recommends https://datacarpentry.org/rr-organization1/01-file-naming/
- @libcce has used Dryad’s guide https://datadryad.org/pages/reusabilityBestPractices

Perhaps an activity would help to demonstrate the concepts?

**Comment by drjwbaker** [comment]
For info, the filenaming discussion is based on my thinking at https://programminghistorian.org/en/lessons/preserving-your-research-data I like the DC R section that @jt14den recommends. I think we should integrate the principles of that, and push reader to the R DC lesson for further reading.

**Comment by libcce** [comment]
@ccronje Jenny Bryan uses the DC R content in her slides on file naming as well: https://speakerdeck.com/jennybc/how-to-name-files. The DC R episode on file naming doesn't have an exercise btw. 

Maybe we can spin the NO and YES section into an exercise? For instance, how can we improve the file naming in the NO section? Based on an initial overview of the core principles.

I found this catalog of bad file naming which might be helpful as well:
http://20px.com/blog/2015/07/16/catalogue-bad-file-naming/
Instead of listing all the NO example, this catalog seems useful in organizing by the different types of bad file naming.

**Comment by libcce** [comment]
The new Workshop Overview lesson addresses these points, particularly file naming and formatting https://librarycarpentry.org/lc-overview/06-file-naming-formatting/index.html. Thanks for the feedback! If there is no further responses we can close this issue.

**Comment by ccronje** [comment]
Agree, the content is a solid start, thanks!
