### ISSUE TITLE
Include information and simple example of using backreferences 

### ISSUE THREAD

**Issue by andrewrs** [LibraryCarpentry/lc-data-intro#72]
I've found that once people learn about backreferences and their potential use, they begin to see some of the incredibly time-saving things that can be accomplished with regular expressions.

I think a very basic example of using backreferences would be a good addition. Granted this addition might not be feasible within the constraints of 20 minutes of teaching time and 25 minutes for exercises and practice.  However, I do think that the topic of regular expressions could warrant a longer, more involved lesson.

**Comment by libcce** [comment]
+1 I've been teaching backreferences in my workshops and I got a lot of nods at my last workshop about using this to clean records/files. I also feel like it is good to touch upon this for possible use in the OpenRefine lesson.

**Comment by drjwbaker** [comment]
Thanks for the suggestion @andrewrs. To do backreferences won't attendees need to learn first about assigning values to groups? We don't cover this either (in fact, we don't really cover groups), so I'm wondering if this is going a little too far. The premise of the lesson is to learn the regex syntax as a general(ish) purpose 'language' in computational work, rather than learn various aspects of full-blown implementation (we usually recommend the exercises are done with pen and paper). Perhaps making a better stab at groups would be what this lesson needs.

**Comment by andrewrs** [comment]
@drjwbaker Yes, they'd also need to know about grouping.  And I do think effectively explaining grouping and backreferences within the allotted time for this lesson might not be easily possible.  I'm more making the argument that regular expressions do deserve a longer lesson more than pointing out an omission.

**Comment by drjwbaker** [comment]
Resolved by https://github.com/LibraryCarpentry/lc-data-intro/pull/73
