### ISSUE TITLE
Modifying language in LC:Intro:Foundations 

### ISSUE THREAD

**Issue by cnorton86** [LibraryCarpentry/lc-data-intro#87]
I'd recommend finding another way to describe the "The computer is stupid" entry in the Foundations lesson (https://librarycarpentry.org/lc-data-intro/03-foundations/index.html). Based on the Carpentries emphasis on inclusive language, this phrasing choice seems to be in conflict.

**Comment by drjwbaker** [comment]
Thanks @cnorton86. Perhaps change to:

`The computer is a machine`

`People interpret. Machines don't. Given a repetitive task, an enumerative task, or a task that relies on memory, a computer can produce results faster, more accurately, and less grudgingly than a person might. But a computer only does what you tell it to. If you get an error message, it is often not your fault! In most cases the computer has failed to interpret what you mean because it can only work with what it knows.`

**Comment by cnorton86** [comment]
I like it! Accurate, easy to read and in alignment with the tone of the lesson while updating the language. Thanks @drjwbaker for working on this.

**Comment by drjwbaker** [comment]
Thanks @cnorton86. Closing as PR https://github.com/LibraryCarpentry/lc-data-intro/pull/89 now up.
